### ISSUE TITLE
ページ構成

### ISSUE THREAD

**Issue by TakuroOnoda** [gitobi/karakuri-farm-web#8]
ログインして、左側にタブ、真ん中にグラフ、弄って保存。みたいな。

イメージ的にはこういう感じで良い？
http://web-cre.info/post-375/

**Comment by deraru** [comment]
よいと思う

**Comment by TakuroOnoda** [comment]
何から手を付けるかなー。とりあえず表示できるようにしたいなー。
今さ、「デバイスの所有者情報（誰がどのデバイスもってる？）」と、「デバイスの関係情報（このjoroとhimawariが関連している）」が無いじゃんね。
これを追加してほしいんだよね、bastet側に。
