### ISSUE TITLE
ログインに関するcognitoとbastetの関係

### ISSUE THREAD

**Issue by TakuroOnoda** [gitobi/karakuri-farm-web#81]
#### ログイン処理とbastet-api
1. KFでログインボタンを押す
2. cognitoファイア、ログイン処理。idToken/refreshTokenをlocalStorageに保持。
3. 以降、kf->bastet間の通信は、idTokenを使ってログイン者を随時確認する。

#### ブラウザリロードに対するログイン状態の復元
1. ブラウザリロード
2. localStrageからtokenを復元。なければ未ログイン状態とする。
3. bastetと通信。時間切れであればKFの裏処理でrefreshTokenを使ってcognitoから新しいtokenをもらう。

**Comment by TakuroOnoda** [comment]
#82 で、ログイン処理とブラウザリロードに対応。
残タスクとして、「bastetとの通信時にtokenを使用する」を実装する必要あり。

**Comment by deraru** [comment]
出来てる
